volumes:
  # Only in the web container.
  # For steamcmd files and resource files used by the scripts.
  homedir_main:

  # Shared by all containers.
  # Mods.
  mods:
  # Server files
  serverfiles:
  # Upstream mission files
  mpmissions:

services:

  web:
    build:
      context: web
      args:
        - USER_ID
    user: ${USER_ID}
    hostname: web
    volumes:
      - homedir_main:/home/user
      - serverfiles:/serverfiles
      - mpmissions:/serverfiles/mpmissions
      - mods:/serverfiles/steamapps/workshop/content
      - mods:/mods
      - ./files:/files
      - ./web:/web
    ports:
      - "8000:8000/tcp"
    restart: no
    env_file:
      - .env
