services:
  dayz:
    build:
      context: .
      args:
        - USER_ID
    user: ${USER_ID}
    volumes:
      - ~/dayz:/home/user
    network_mode: host
    # The above is mutually exclusive with the below. If you don't need
    # the server to show up on the LAN, comment out the network_mode above
    # and uncomment the port mappings below.
    #    ports:
    #       # Game port
    #      - 2302:2302/udp
    #       # RCON port
    #      - 2303:2303/udp
    #       # Steam port
    #      - 27016:27016/udp
    env_file:
      - .env
