volumes:
  # Only in the web container.
  # For steamcmd files and resource files used by the scripts.
  homedir:

  # Shared by all containers.
  # Mods.
  mods:
  # Server files for release
  serverfiles:
  # Server files for experimental
  serverfiles_experimental:
  # Upstream mission files
  mpmissions:
  mpmissions_experimental:

services:

  web:
    build:
      context: web
      args:
        - USER_ID
    user: ${USER_ID}
    hostname: dayzdockerserver
    volumes:
      - homedir:/home/user
      - serverfiles:/serverfiles
      - serverfiles_experimental:/serverfiles_experimental
      - mpmissions:/serverfiles/mpmissions
      - mpmissions_experimental:/serverfiles_experimental/mpmissions
      - mods:/serverfiles/steamapps/workshop/content
      - mods:/mods
      - ./files:/files
      - ./web:/web
    ports:
      - "8000:8000/tcp"
    restart: no
    env_file:
      - .env
